max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
edition = "2021"
merge_derives = true
use_try_shorthand = false
use_field_init_shorthand = false
force_explicit_abi = true
empty_item_single_line = true
struct_lit_single_line = true
fn_single_line = false
where_single_line = false
imports_indent = "Block"
imports_layout = "Vertical"
reorder_impl_items = false
type_punctuation_density = "Compressed"
space_before_colon = false
space_after_colon = true
spaces_around_ranges = false
binop_separator = "Front"
remove_blank_lines_at_start_or_end_of_blocks = false
match_block_trailing_comma = false
trailing_comma = "Vertical"
trailing_semicolon = true
comment_width = 80
normalize_comments = false
normalize_doc_attributes = false
wrap_comments = false
format_code_in_doc_comments = true