# CLAUDE DLS Production Configuration
# Complete production-ready configuration for diskless boot system

[server]
bind_address = "0.0.0.0:8080"
worker_threads = 8
max_connections = 1000
request_timeout = 30
keep_alive_timeout = 60
graceful_shutdown_timeout = 30

[database]
url = "postgresql://claude_dls:${POSTGRES_PASSWORD}@postgres:5432/claude_dls_production"
max_connections = 100
min_connections = 10
connection_timeout = 30
idle_timeout = 600
max_lifetime = 3600
ssl_mode = "prefer"

[authentication]
jwt_secret = "${JWT_SECRET}"
token_expiry_hours = 24
password_hash_cost = 12
session_timeout_minutes = 480
max_failed_attempts = 5
lockout_duration_minutes = 15

[storage]
base_path = "/var/lib/claude_dls/images"
zfs_pool = "claude_images"
max_image_size_gb = 100
compression = "lz4"
deduplication = true
snapshot_retention_days = 30
default_format = "raw"

[network]
dhcp_enabled = true
dhcp_interface = "eth0"
dhcp_range_start = "192.168.100.100"
dhcp_range_end = "192.168.100.200"
dhcp_lease_time = 7200
dhcp_server_ip = "192.168.100.1"
dhcp_subnet_mask = "255.255.255.0"
dhcp_gateway = "192.168.100.1"
dhcp_dns_servers = ["8.8.8.8", "8.8.4.4"]

tftp_enabled = true
tftp_root = "/var/lib/claude_dls/tftp"
tftp_interface = "0.0.0.0"
tftp_port = 69

iscsi_enabled = true
iscsi_portal = "0.0.0.0:3260"
iscsi_target_prefix = "iqn.2024-01.local.claude"
iscsi_chap_enabled = true

[monitoring]
metrics_enabled = true
metrics_endpoint = "/metrics"
metrics_bind_address = "0.0.0.0:9090"
prometheus_namespace = "claude_dls"
health_check_endpoint = "/health"
stats_interval_seconds = 60

[logging]
level = "info"
format = "json"
output = "stdout"
max_file_size = "100MB"
max_files = 10
compress_rotated = true

[security]
cors_enabled = true
cors_allowed_origins = ["http://localhost:3000", "https://claude.local"]
cors_allowed_methods = ["GET", "POST", "PUT", "DELETE"]
cors_allowed_headers = ["Content-Type", "Authorization"]
rate_limiting_enabled = true
rate_limit_requests_per_minute = 60
csrf_protection = true
secure_headers = true

[performance]
worker_keep_alive = true
tcp_nodelay = true
socket_reuse = true
backlog = 1024
client_timeout = 30
client_shutdown = 5

[features]
pxe_boot = true
uefi_boot = true
legacy_boot = true
windows_support = true
linux_support = true
custom_images = true
snapshot_boot = true
multicast_imaging = false
auto_provisioning = true

[boot]
default_boot_menu_timeout = 10
boot_menu_title = "CLAUDE DLS Boot Menu"
default_os = "local"
pxe_menu_background = "/var/lib/claude_dls/tftp/background.png"
boot_password_protected = false

[api]
enable_swagger = true
swagger_ui_path = "/api/docs"
api_version = "v1"
max_request_size = "100MB"
enable_compression = true
compression_level = 6

[backup]
enabled = true
schedule = "0 2 * * *"  # Daily at 2 AM
retention_days = 30
backup_path = "/var/lib/claude_dls/backups"
compress_backups = true
encrypt_backups = false

[maintenance]
auto_cleanup_enabled = true
cleanup_schedule = "0 3 * * 0"  # Weekly on Sunday at 3 AM
temp_file_retention_hours = 24
log_retention_days = 30
metrics_retention_days = 90

[notifications]
enabled = false
email_enabled = false
smtp_server = ""
smtp_port = 587
smtp_username = ""
smtp_password = ""
admin_email = ""
alert_threshold_disk_usage = 90
alert_threshold_memory_usage = 85
alert_threshold_cpu_usage = 80

[development]
debug_mode = false
hot_reload = false
mock_storage = false
test_mode = false
profiling_enabled = false

# Environment-specific overrides
[production]
debug_assertions = false
panic_strategy = "abort"
opt_level = 3
lto = true
codegen_units = 1

[staging]
debug_assertions = true
panic_strategy = "unwind"
opt_level = 2
lto = false

[testing]
mock_storage = true
test_mode = true
debug_assertions = true